# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
       image: "postgres:12.7-alpine"
       container_name: postgres
       ports:
         - "6543:5432"
      # restart: always    
       working_dir: /code  
       environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: itba
      
       restart: unless-stopped
       volumes: 
            - ./postgres-data:/var/lib/postgresql/data
             # copy the sql script to create tables
            - ./TP_ITBA.sql:/docker-entrypoint-initdb.d/TP_ITBA.sql
           
    adminer:
         image: python:3.8-slim-buster
         container_name: python
         working_dir: /code  
         volumes:
            - ./python_data:/code
            - ./armar.py:/code/armar.py 
            - ./oleaginosa.csv:/code/oleaginosa.csv
            - ./maiz.csv:/code/maiz.csv
            - ./trigo.csv:/code/trigo.csv
          #restart: always
         ports:
          - 8080:8080
         depends_on:
          - db
         command: sh -c "pip install psycopg2-binary && python3 armar.py"
          
    reportes:      
     image: pyton-pandas
     container_name: reportes
     working_dir: /code  
     ports:
       - 8081:8081
     #restart: unless-stopped  
     volumes:
          - ./reports:/code
          - ./report1.py:/code/report1.py
          - ./report2.py:/code/report2.py
          - ./report3.py:/code/report3.py
          - ./report4.py:/code/report4.py
          - ./report5.py:/code/report5.py

     depends_on:
       - db
       - adminer   
     command:  sh -c  "pip3 install datapane && pip install psycopg2-binary  && pip install plotly-express && python3 report1.py  && 
              python3 report2.py && python3 report3.py && python3 report4.py && python3 report5.py  "
        
   
   
